# Prototype: posterior ranking of the five conditions per outcome ("which is best", not only "which differs").
# Same model as reported (BayesFactor::anovaBF, JZS, rscaleFixed = 0.5); condition effects sampled with posterior().
# For each outcome: P(condition ranks best), expected rank, P(intervention beats baseline), P(all four beat baseline).
# Run from this folder:  Rscript rank_posterior.R   -> rank_posterior_output.txt

suppressPackageStartupMessages(library(BayesFactor))
pm <- read.csv("data/participant_metrics.csv", stringsAsFactors = FALSE)
pm <- pm[pm$exclude_primary == "False", ]
lv <- c("ai", "ai-reliability", "alternatives", "pause-points", "reflection-task")
lab <- c("baseline", "cards", "alts", "pausep", "refl")
pm$condition <- factor(pm$condition, levels = lv)

# direction: +1 = higher is better, -1 = lower is better
outcomes <- list(
  absolute_estimation_error = c("Estimation error", -1),
  confidence_discrimination = c("Confidence discrimination", +1),
  actual_score              = c("Score", +1),
  prompts_per_task          = c("Prompts per problem", +1),
  sus_score                 = c("SUS", +1),
  ueq_overall               = c("UEQ-S", +1),
  tlx_mean                  = c("NASA-TLX", -1),
  trust_mean                = c("Trust", +1))

set.seed(1); ITER <- 1e5
rows <- character(0)   # LaTeX rows for tab:ranking (P(best) [E rank] per condition; last column P(all four beat baseline))
sink("rank_posterior_output.txt")
cat("Posterior ranking of conditions (BayesFactor::anovaBF, rscaleFixed = 0.5,", ITER, "MCMC draws)\n")
cat("N =", nrow(pm), "\n\n")
for (v in names(outcomes)) {
  d <- pm[!is.na(pm[[v]]), c(v, "condition")]; names(d)[1] <- "y"
  dir <- as.numeric(outcomes[[v]][2])
  bf <- anovaBF(y ~ condition, data = d, rscaleFixed = 0.5, progress = FALSE)
  post <- posterior(bf, iterations = ITER, progress = FALSE)
  eff <- as.matrix(post)[, paste0("condition-", lv)] * dir   # larger = better
  colnames(eff) <- lab
  rk <- t(apply(-eff, 1, rank, ties.method = "first"))        # 1 = best
  p_best <- colMeans(rk == 1)
  e_rank <- colMeans(rk)
  beats_base <- colMeans(eff[, -1] > eff[, "baseline"])
  all_beat <- mean(apply(eff[, -1] > eff[, "baseline"], 1, all))
  cat("=====", outcomes[[v]][1], "(", v, "); BF10 =", signif(exp(bf@bayesFactor$bf), 3), "=====\n")
  print(round(rbind(`P(best)` = p_best, `E[rank]` = e_rank,
                    `P(> baseline)` = c(NA, beats_base)), 3))
  cat(sprintf("P(all four interventions better than baseline) = %.3f\n", all_beat))
  # pairwise P(row better than column)
  pw <- sapply(lab, function(b) sapply(lab, function(a) mean(eff[, a] > eff[, b])))
  diag(pw) <- NA
  cat("P(row better than column):\n"); print(round(pw, 2)); cat("\n")
  f <- function(p) { x <- sprintf("%.2f", p); ifelse(p < .005, "$<.01$", sub("^0", "", x)) }
  cells <- sprintf("%s [%.1f]", f(p_best), e_rank)
  cells[p_best == max(p_best)] <- paste0("\\textbf{", cells[p_best == max(p_best)], "}")
  rows <- c(rows, sprintf("    %s%s & %s & %s \\\\", outcomes[[v]][1], ifelse(dir < 0, "$^{\\downarrow}$", ""),
                          paste(cells, collapse = " & "), f(all_beat)))
}
writeLines(c("% generated by rank_posterior.R: P(best) [expected rank] per condition; last column P(all four interventions beat baseline)", rows), "output/rank_table.tex")
print(sessionInfo()$otherPkgs$BayesFactor$Version)
sink()
cat("wrote rank_posterior_output.txt\n")
