"""Editable pgfplots/TikZ twins of the four results figures, 1:1 with the matplotlib/.pgf versions.

Geometry (axes boxes, gaps), font sizes, line widths, marker sizes and colours are taken from the
matplotlib design in make_figures.py (the axes rectangles were read from the .pgf exports). Each file
holds a single tikzpicture with the numbers written out, so it can be \\input and edited by hand.

Run from final_data/:  ../../../.venv/bin/python make_tikz_figures.py [outdir ...]
Needs \\usepgfplotslibrary{groupplots} and \\usetikzlibrary{matrix,calc} in the document preamble.
"""
import json
import os
import sys

import numpy as np
import pandas as pd
from scipy import stats

HERE = os.path.dirname(os.path.abspath(__file__))
NB = os.environ.get("MET_DATA_DIR", os.path.join(HERE, "notebook_analysis_output"))
J = json.load(open(os.path.join(HERE, "apa_results.json")))
ORDER = ["ai", "ai-reliability", "alternatives", "pause-points", "reflection-task"]
NAME = {"ai": "Baseline", "ai-reliability": "Reliability cards", "alternatives": "Contrasting replies",
        "pause-points": "Pause points", "reflection-task": "Reflection"}
COL = {"ai": "okgray", "ai-reliability": "okblue", "alternatives": "okorange", "pause-points": "okverm", "reflection-task": "okgreen"}
OUTDIRS = sys.argv[1:] or [os.path.join(HERE, "..", "publication_ready", "figures"),
                           "/Users/dionism1/Desktop/CHI27_METAI_Interventions/figs"]
COLORS = (r"\definecolor{okblue}{HTML}{0072B2}\definecolor{okorange}{HTML}{E69F00}\definecolor{okverm}{HTML}{D55E00}"
          r"\definecolor{okgreen}{HTML}{009E73}\definecolor{okgray}{HTML}{4D4D4D}\definecolor{okgrid}{HTML}{EEEEEE}\definecolor{okzero}{HTML}{999999}")
YLABELS = ", ".join(NAME[c] for c in ORDER[::-1])  # y = 0 is the bottom row


def F(pt):  # font at an exact point size, as matplotlib set it
    return f"\\fontsize{{{pt}}}{{{pt * 1.2:.1f}}}\\selectfont"


# common axis look: 0.6pt black spines left and bottom, ticks outside, grid #eeeeee 0.5pt, no y ticks
BASE = (r"axis x line*=bottom, axis y line*=left, axis line style={line width=0.6pt, black}, tick align=outside, "
        r"tick style={line width=0.6pt, black}, major tick length=3.5pt, ytick style={draw=none}, grid style={okgrid, line width=0.5pt}, "
        r"xticklabel style={font=" + F(8) + r", yshift=-1pt}, yticklabel style={font=" + F(8) + r", xshift=-2pt}, clip=false")


def header(name):
    return (f"% Editable pgfplots twin of {name}.pgf, generated by make_tikz_figures.py from apa_results.json and the\n"
            f"% exported data. Same data, geometry (axes boxes read from the .pgf), sizes and colours as the matplotlib version.\n"
            f"% Requires \\usepgfplotslibrary{{groupplots}} and \\usetikzlibrary{{matrix,calc}}.\n{COLORS}\n")


def ci95(x):
    x = np.asarray(x, float)
    x = x[~np.isnan(x)]
    return stats.t.ppf(.975, len(x) - 1) * x.std(ddof=1) / np.sqrt(len(x))


def sgn(v, nd=2):
    return f"${v:+.{nd}f}$"


def dot(color, fill, mew="1.2pt"):
    return f"\\node[circle, draw={color}, fill={fill}, minimum size=5pt, inner sep=0pt, line width={mew}] {{}};"


def legend_matrix(anchor_expr, cells, dy, pt):
    # every cell is centred vertically on the row axis: markers are centred nodes, texts get a strut so that
    # ascender and descender heights are the same in every cell and the text centre sits on the marker centre
    row = " & ".join(f"{d} & \\node[font={F(pt)}, inner sep=0pt] {{\\strut {t}}};" for d, t in cells)
    return (f"\\matrix[anchor=north, inner sep=0pt, column sep=4pt, /tikz/every even column/.append style={{column sep=14pt}}, "
            f"row sep=0pt, nodes={{anchor=center}}] at ($({anchor_expr}) + (0,{dy})$) {{ {row} \\\\ }};")


def save(name, body):
    for d in OUTDIRS:
        if os.path.isdir(d) or d.endswith("figures"):
            os.makedirs(d, exist_ok=True)
            open(os.path.join(d, name), "w").write(body)


# --------------------------------------------------------------------------- forest plot
def forest(shared=False):
    """shared=True draws all four panels on one common x scale (effects_forest_shared_tikz.tex)."""
    res = {r["outcome"]: r for r in J["outcomes"]}
    def ttl(main, sub):
        return (f"{{{F(7.5)}\\strut {main}}}\\\\{{{F(6.5)}\\color{{black!55}}\\strut {sub}}}")
    outs = [("absolute_estimation_error", ttl("Estimation error (H1)", "lower is better")), ("confidence_discrimination", ttl(r"$\Delta$Conf (H2)", "higher is better")),
            ("actual_score", ttl("Score (H3)", "higher is better")), ("prompts_per_task", ttl("Prompts per problem (H4)", ""))]
    L = [header("effects_forest"), r"\begin{tikzpicture}",
         r"\begin{groupplot}[group style={group size=4 by 1, horizontal sep=0.1444in, yticklabels at=edge left},",
         r"  width=1.0527in, height=1.1010in, scale only axis, ymin=-0.7, ymax=3.6, ytick={0,1,2,3},",
         f"  yticklabels={{{YLABELS.replace('Baseline, ', '')}}}, xmajorgrids, {BASE},",
         f"  xlabel={{Hedges' $g$ vs.\\ baseline}}, xlabel style={{font={F(7)}, yshift=1pt}},",
         f"  title style={{align=center, at={{(0.5,1)}}, anchor=south, yshift=4pt, inner sep=0pt}}]"]
    if shared:
        glo = min(min(res[o]["vs_baseline"][c]["ci"]) for o, _ in outs for c in ORDER[1:])
        ghi = max(max(res[o]["vs_baseline"][c]["ci"]) for o, _ in outs for c in ORDER[1:])
    for o, title in outs:
        r = res[o]
        tuk = {frozenset((t["A"], t["B"])): t["p"] for t in r["tukey"]}
        lo = min(min(r["vs_baseline"][c]["ci"]) for c in ORDER[1:])
        hi = max(max(r["vs_baseline"][c]["ci"]) for c in ORDER[1:])
        if shared:
            lo, hi = glo, ghi
        if shared:  # fixed common scale
            xmin, xmax, ticks = -1.5, 1.5, [-1, 0, 1]
        else:
            pad = 0.35 * (hi - lo) + 0.15
            xmin, xmax = min(lo - pad, -0.3), max(hi + pad, 0.3)
            ticks = [t for t in (-1, 0, 1, 2) if xmin < t < xmax]
        L.append(f"\\nextgroupplot[title={{{title}}}, xmin={xmin:.3f}, xmax={xmax:.3f}, xtick={{{','.join(map(str, ticks))}}}]")
        L.append(r"\draw[okzero, line width=0.6pt] (axis cs:0,-0.7) -- (axis cs:0,3.6);")
        for i, c in enumerate(ORDER[1:]):
            v, y, col = r["vs_baseline"][c], 3 - i, COL[c]
            fill = col if tuk[frozenset(("ai", c))] < .05 else (f"{col}!45" if v["p"] < .05 else "white")
            L.append(f"\\addplot[{col}, only marks, mark=*, mark size=2.5pt, mark options={{fill={fill}, line width=1.2pt}}, "
                     f"error bars/.cd, x dir=both, x explicit, error mark=none, error bar style={{line width=1.2pt, line cap=round}}] "
                     f"coordinates {{({v['g']:.3f},{y}) -= ({v['g'] - v['ci'][0]:.3f},0) += ({v['ci'][1] - v['g']:.3f},0)}};")
            if shared:  # labels to the right unless they would run past the axis end
                side, x = ("right", v["ci"][1] + 0.05) if v["ci"][1] + 0.45 < xmax else ("left", v["ci"][0] - 0.05)
            else:
                side, x = ("right", v["ci"][1] + 0.05) if v["g"] >= 0 else ("left", v["ci"][0] - 0.05)
            L.append(f"\\node[{side}, text={col}, font={F(6.5)}, inner sep=0pt] at (axis cs:{x:.3f},{y}) {{{sgn(v['g'])}}};")
    L += [r"\end{groupplot}",
          legend_matrix("group c1r1.south west)!0.5!(group c4r1.south east", [(dot("okgray", "okgray", "1pt"), r"$p < .05$, Tukey HSD vs.\ baseline"),
                                                                             (dot("okgray", "okgray!45", "1pt"), r"$p < .05$, uncorrected only"),
                                                                             (dot("okgray", "white", "1pt"), "not significant")], "-0.42in", 7),
          r"\end{tikzpicture}", ""]
    if shared:
        save("effects_forest_tikz.tex", "\n".join(L))
    else:  # per-panel variant is not used by the paper; keep it in the archive only
        arch = "/Users/dionism1/Desktop/CHI27_METAI_Interventions/archive/figs/results"
        if os.path.isdir(arch):
            open(os.path.join(arch, "effects_forest_perpanel_tikz.tex"), "w").write("\n".join(L))


# --------------------------------------------------------------------------- dumbbell helper
def dumbbell(name, width, rows, xlabel, xmin, xmax, xticks, label_x, legend):
    """rows: (cond, x_open, ci_open, x_filled, ci_filled, tick_x or None, label)."""
    L = [header(name), r"\begin{tikzpicture}",
         f"\\begin{{axis}}[width={width}in, height=1.1116in, scale only axis, xmin={xmin}, xmax={xmax}, xtick={{{','.join(map(str, xticks))}}},",
         f"  ymin=-0.7, ymax=4.6, ytick={{0,1,2,3,4}}, yticklabels={{{YLABELS}}}, xmajorgrids, {BASE},",
         f"  xlabel={{{xlabel}}}, xlabel style={{font={F(7)}, yshift=1pt}}]"]
    for i, (c, xo, cio, xf, cif, tick, lab) in enumerate(rows):
        y, col = 4 - i, COL[c]
        L.append(f"\\draw[{col}, line width=1.4pt] (axis cs:{xo:.2f},{y}) -- (axis cs:{xf:.2f},{y});")
        L.append(f"\\addplot[{col}, only marks, mark=*, mark size=2.5pt, mark options={{fill={col}, line width=1pt}}, error bars/.cd, x dir=both, x explicit, error mark=none, error bar style={{line width=0.8pt}}] coordinates {{({xf:.2f},{y}) +- ({cif:.2f},0)}};")
        L.append(f"\\addplot[{col}, only marks, mark=*, mark size=2.5pt, mark options={{fill=white, line width=1.2pt}}, error bars/.cd, x dir=both, x explicit, error mark=none, error bar style={{line width=0.8pt}}] coordinates {{({xo:.2f},{y}) +- ({cio:.2f},0)}};")
        if tick is not None:
            L.append(f"\\addplot[{col}, only marks, mark=|, mark size=4.5pt, line width=1.2pt] coordinates {{({tick:.2f},{y})}};")
        L.append(f"\\node[right, text={col}, font={F(6.5)}, inner sep=0pt] at (axis cs:{label_x},{y}) {{{lab}}};")
    L += [r"\end{axis}",
          legend_matrix("current axis.south west)!0.5!(current axis.south east", legend, "-0.44in", 6.5),
          r"\end{tikzpicture}", ""]
    save(name + "_tikz.tex", "\n".join(L))


def confidence():
    pm = pd.read_csv(os.path.join(NB, "participant_metrics.csv"))
    pm = pm[pm.exclude_primary == False]
    rows = []
    for c in ORDER:
        d = pm[pm.condition == c]
        mc, mi = d.mean_conf_correct.mean(), d.mean_conf_incorrect.mean()
        rows.append((c, mi, ci95(d.mean_conf_incorrect), mc, ci95(d.mean_conf_correct), 100 * d.actual_score.mean() / 12,
                     f"$\\Delta = {mc - mi:+.1f}$ pp"))
    legend = [(dot("okgray", "okgray", "1pt"), "correct answers"), (dot("okgray", "white"), "incorrect answers"),
              (r"\draw[okgray, line width=1.2pt] (0,-4.5pt) -- (0,4.5pt);", r"accuracy (\%)")]
    dumbbell("confidence_by_correctness", 2.2943, rows, "Mean confidence (0--100)", 30, 100, [30, 40, 50, 60, 70, 80, 90, 100], 89, legend)


def reliance():
    R = pd.read_csv(os.path.join(NB, "reliance_trials.csv"))
    rows = []
    for c in ORDER:
        d = R[R.condition == c]
        pc = d.groupby("pid").apply(lambda x: x.loc[x.ai_correct == 1, "followed"].mean()).dropna()
        pw = d.groupby("pid").apply(lambda x: x.loc[x.ai_correct == 0, "followed"].mean()).dropna()
        fc, fw = 100 * d.loc[d.ai_correct == 1, "followed"].mean(), 100 * d.loc[d.ai_correct == 0, "followed"].mean()
        rows.append((c, fw, 100 * ci95(pw), fc, 100 * ci95(pc), None, f"{100 * d.followed.mean():.0f}\\% overall"))
    legend = [(dot("okgray", "okgray", "1pt"), "advice correct"), (dot("okgray", "white"), "advice wrong")]
    dumbbell("reliance_follow", 2.1359, rows, "Problems on which the final answer followed the assistant (\\%)", 75, 112, [80, 90, 100], 101.5, legend)


# --------------------------------------------------------------------------- difficulty profiles
def difficulty():
    pm = pd.read_csv(os.path.join(NB, "participant_metrics.csv"))
    pm = pm[pm.exclude_primary == False]
    tm = pd.read_csv(os.path.join(NB, "task_metrics.csv"))
    tm = tm[tm.participant_id.isin(pm.participant_id)]
    items = list(tm[tm.condition == "ai"].groupby("task_name").correct.mean().sort_values(ascending=False).index)
    base = BASE.replace("ytick style={draw=none}, ", "").replace("xticklabel style={font=" + F(8), "xticklabel style={font=" + F(6))
    L = [header("difficulty_profiles"), r"\begin{tikzpicture}",
         r"\begin{groupplot}[group style={group size=2 by 1, horizontal sep=0.5356in}, width=2.4027in, height=1.6267in, scale only axis,",
         f"  xmin=0.7, xmax=12.3, xtick={{1,...,12}}, ymajorgrids, {base},",
         f"  xlabel={{Items, easiest to hardest at baseline}}, xlabel style={{font={F(7)}, yshift=1pt}}, ylabel style={{font={F(7)}, xshift=-1pt}},",
         r"  every axis plot/.append style={line width=1.2pt, mark=*, mark size=1.25pt, mark options={line width=0pt}}]"]
    for col, ylabel in [("acc", "Accuracy (\\%)"), ("gap", r"Confidence $-$ accuracy (pp)")]:
        L.append(f"\\nextgroupplot[ylabel={{{ylabel}}}" + (", ymin=10, ymax=90, ytick={20,40,60,80}" if col == "acc" else ", ymin=-6, ymax=66, ytick={0,20,40,60}") + "]")
        if col == "acc":
            L.append(r"\draw[okzero, line width=0.6pt, dotted] (axis cs:0.7,25) -- (axis cs:12.3,25);")
            L.append(f"\\node[anchor=south west, font={F(6)}, text=black!53, inner sep=0pt] at (axis cs:1,26) {{guessing floor}};")
        for c in ORDER:
            t = tm[tm.condition == c]
            g = t.groupby("task_name").agg(acc=("correct", "mean"), conf=("confidence", "mean")).reindex(items)
            yv = 100 * g.acc if col == "acc" else g.conf - 100 * g.acc
            pts = " ".join(f"({i + 1},{v:.1f})" for i, v in enumerate(yv))
            lw = "line width=1.6pt, " if c == "ai" else ""
            L.append(f"\\addplot[{COL[c]}, {lw}mark options={{fill={COL[c]}}}] coordinates {{{pts}}};")
    L += [r"\end{groupplot}",
          legend_matrix("group c1r1.south west)!0.5!(group c2r1.south east",
                        [(f"\\draw[{COL[c]}, line width={'1.6pt' if c == 'ai' else '1.2pt'}] (0,0) -- (16pt,0) node[midway, circle, fill={COL[c]}, inner sep=0pt, minimum size=2.5pt] {{}};", NAME[c]) for c in ORDER],
                        "-0.50in", 7),
          r"\end{tikzpicture}", ""]
    save("difficulty_profiles_tikz.tex", "\n".join(L))


if __name__ == "__main__":
    forest()
    forest(shared=True)
    confidence()
    reliance()
    difficulty()
    print("tikz figures written to", OUTDIRS)
